from automata.fa.Moore import Moore
from read_file import FileOpen
import sys

estados = ['q0', 'INT-i', 'INT-n', 'INT-t', 'INT-*',
           'FLOAT_F', 'FLOAT_L', 'FLOAT_O', 'FLOAT_A', 'FLOAT_T', 'FLOAT_*',
            'ID', 'ID*', 'ID_LPAREN', 'LRPAREN',
            'RETURN_R','RETURN_E', 'RETURN_T', 'RETURN_U', 'RETURN_R2', 'RETURN_E', 'RETURN_N', 'RETURN_*', 'RETURN_RPAREN',
            'VOID_V', 'VOID_O', 'VOID_I', 'VOID_D', 'VOID_)', 'VOID_*', 'VOID_RPAREN_LBRACES']

lenguage = ['a','b','c','d', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0','1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '<', '>', '=']
saidas = ['INT']

moore = Moore(estados,
              lenguage,
              saidas,
              {
                #ESTADO INICIAL
                'q0':{
                    'i'  : 'INT-i',         #int
                    'v'  : 'VOID_V',        #VOID
                    'r'  : 'RETURN_R',      #return
                    ' '  : 'q0',            #FICA EM LOOP 
                    '}'  : 'RBRACES',       #RBRACES
                    '{'  : 'LBRACES',       #LBRACES
                    'f'  : 'FLOAT_F',       #FLOAT
                    '('  : 'LPAREN',        #LPAREN
                    ')'  : 'RPAREN',
                    '='  : 'ATTRIBUTION',   #ATTRIBUTION
                    '<'  : 'LESS',
                    '>'  : 'GREATER',
                    '==' : 'EQUALS',
                    'e'  : 'ELSE_E',
                    '+'  : 'PLUS',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 

                    '0' : 'NUMBER',
                    '1' : 'NUMBER',
                    '2' : 'NUMBER', 
                    '3' : 'NUMBER',
                    '4' : 'NUMBER',
                    '5' : 'NUMBER',
                    '6' : 'NUMBER',
                    '7' : 'NUMBER',
                    '8' : 'NUMBER',
                    '9' : 'NUMBER',
                },

                #------------------F L O A T-------------------------
                'FLOAT_F':{
                    'l' : 'FLOAT_L',
                    'o' : 'FOR_O',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'n' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_L':{
                    'o' : 'FLOAT_O',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_O':{
                    'a' : 'FLOAT_A',
                    
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_A':{
                    't' : 'FLOAT_T',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',   
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_T':{
                    ' ' : 'FLOAT_*',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_*':{
                    ' ' : 'q0',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                #------------------I N T-------------------------
                'INT-i':{
                    'n' : 'INT-n',
                    ' ' : 'ID*',
                    'f' : 'IF_F',
                    

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID',
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID',
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID',
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'x' : 'ID',
                    'z' : 'ID', 
                },

                'INT-n':{
                    't' : 'INT-t',
                    ' ' : 'ID*',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID',
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID',
                    'n' : 'ID', 
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID',
                    'r' : 'ID', 
                    's' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID',
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'x' : 'ID',
                    'z' : 'ID',
                },

                'INT-t':{
                    ' ' : 'INT-*',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID',
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID',
                    'n' : 'ID', 
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID',
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID',
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'x' : 'ID',
                    'z' : 'ID',
                },

                'INT-*':{
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID',
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 

                },

                #------------------I D E N T I F I C A D O R-------------------------
                'ID':{
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID',
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',

                    '0' : 'ID',
                    '1' : 'ID',
                    '2' : 'ID', 
                    '3' : 'ID',
                    '4' : 'ID',
                    '5' : 'ID',
                    '6' : 'ID',
                    '7' : 'ID',
                    '8' : 'ID',
                    '9' : 'ID',


                    ' ' : 'ID*',
                    '(' : 'ID_LPAREN',
                    ',' : 'ID_COMMA',
                    ')' : 'ID_RPAREN',
                    ';' : 'ID_SEMICOLON',
                },

                'ID_SEMICOLON': {
                    'f': 'FOR_F',
                    ' ': 'q0',
                    '}': 'RBRACES'
                },

                'ID_RPAREN': {
                    ' ' : 'q0',
                    ';' : 'SEMICOLON',
                    '{' : 'RBRACES',
                    ')' : 'RPAREN',
                },

                'ID_LPAREN':{
                    'v': 'VOID_V',
                    'i': 'INT-i',
                    ')': 'LPAREN',
                    'f' : 'FLOAT_F',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',

                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                },
                
        

                'ID_COMMA':{
                    ' ': 'q0'
                },
                
                'ID*':{
                    ' ': 'q0',
                    ')': 'LPAREN',
                    '+': 'PLUS',
                    '-': 'MINUS',
                    '*': 'TIMES',
                    '=': 'ATTRIBUTION',
                    ',': 'ID_COMMA',
                    '<': 'LESS',
                    '>': 'GRAETER',
                },

            #---------------------S I N A I S-------------------------
            'PLUS': {
                ' ' : 'q0',
            },

            'MINUS': {
                ' ' : 'q0',
            },

            'TIMES': {
                ' ' : 'q0',
            },

            'ATTRIBUTION': {
                ' ' : 'ATTRIBUTION_*',
                '=' : 'EQUALS'
            },

            'ATTRIBUTION_*': {
                ' ' : 'q0',

                'a' : 'ID',
                'b' : 'ID',
                'c' : 'ID',
                'd' : 'ID',
                'e' : 'ID',
                'f' : 'ID',
                'g' : 'ID',
                'h' : 'ID',
                'i' : 'ID', 
                'j' : 'ID', 
                'k' : 'ID', 
                'l' : 'ID', 
                'm' : 'ID', 
                'n' : 'ID',
                'o' : 'ID', 
                'p' : 'ID', 
                'q' : 'ID', 
                'r' : 'ID', 
                's' : 'ID', 
                't' : 'ID', 
                'u' : 'ID', 
                'w' : 'ID', 
                'y' : 'ID', 
                'z' : 'ID',
                
                '0' : "NUMBER",
                '1' : "NUMBER",
                '2' : "NUMBER",
                '3' : "NUMBER",
                '4' : "NUMBER",
                '5' : "NUMBER",
                '6' : "NUMBER",
                '7' : "NUMBER",
                '8' : "NUMBER",
                '9' : "NUMBER",
            },

            'COMMA': {
                '0' : "NUMBER",
                '1' : "NUMBER",
                '2' : "NUMBER",
                '3' : "NUMBER",
                '4' : "NUMBER",
                '5' : "NUMBER",
                '6' : "NUMBER",
                '7' : "NUMBER",
                '8' : "NUMBER",
                '9' : "NUMBER",
            },

            'LESS':{
                ' ': 'LESS_*',
                '=': 'LESS_EQUAL'
            },

            'LESS_EQUAL': {
                ' ': 'q0',
            },

            'GREATER':{
                ' ': 'GREATER_*',
                '=': '_EQUAL'
            },

            'EQUALS':{
                ' ': 'q0',
            },


            #---------------------P A R E N-------------------------


                'LPAREN':{
                    ' ' : 'q0',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'j' : 'ID', 
                    'i' : 'ID',
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

            #---------------------V O I D-------------------------

                'VOID_V':{
                    'o' : 'VOID_O',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID',
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'VOID_O':{
                    'i' : 'VOID_I',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'VOID_I':{
                    'd' : 'VOID_D',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                
                'VOID_D':{
                    ' ' : 'VOID_*',
                    ')' : 'VOID_)',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },
                
                'VOID_)':{
                    '{' : 'VOID_RPAREN_LBRACES'
                },

                'VOID_RPAREN_LBRACES':{
                    ' ' : 'q0',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },
                #------------------I F / E L S E-------------------------
                
                'IF_I':{
                    'f' : 'IF_F',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'IF_F':{
                    ' ' : 'IF_*',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'f' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'IF_*':{
                    ' ' : 'q0',
                    '(' : 'LPAREN',
                },

                'ELSE_E':{
                    'l' : 'ELSE_L',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'ELSE_L':{
                    's' : 'ELSE_S',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'ELSE_S':{
                    'e' : 'ELSE_E2',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'ELSE_E2':{
                    ' ' : 'ELSE_*',
                    '{' : 'ELSE_LBRACES',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'ELSE_*':{
                    ' ' : 'q0',
                    'r' : 'RETURN_R',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'ELSE_LBRACES':{
                    ' ' : 'q0'
                },


                #------------------R E T U R N-------------------------

                'RETURN_R':{
                    'e' : 'RETURN_E',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'RETURN_E':{
                    't' : 'RETURN_T',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',  
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },
                'RETURN_T':{
                    'u' : 'RETURN_U',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },
                'RETURN_U':{
                    'r' : 'RETURN_R2',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'RETURN_R2':{
                    'n' : 'RETURN_N',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'RETURN_N':{
                    ' ' : 'RETURN_*',
                    '(' : 'RETURN_LPAREN',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',

                },

                'RETURN_LPAREN':{
                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',

                },

                'RETURN_*': {
                    ' ' : 'q0',
                    '(' : 'RPAREN',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',

                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                    '.' : 'NUMBER',
                },

            #------------------NUMBER-------------------------

                'NUMBER':{
                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                    '.' : 'NUMBER',
                    
                    ')' : "NUMBER_RPAREN",
                    ',' : "NUMBER_COMMA",
                    ';' : "NUMBER_SEMICOLON",
                    ' ' : "NUMBER_*",
                },

                'NUMBER_SEMICOLON': {
                    ' ' : 'q0',
                    '}' : 'RBRACES'
                },

                'NUMBER_COMMA':{
                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",

                    ' ' : 'q0'
                },

                'NUMBER_RPAREN':{
                    ';' : "SEMICOLON",
                    '{' : 'LBRACES',
                    ' ' : 'q0',
                },

                'NUMBER_*':{
                    ')': 'RPAREN'
                },

            #------------------S E M I C O L O N-------------------------

                'SEMICOLON':{
                    ' ' : "q0",
                    '}' : 'RBRACES'
                },

            #------------------B R A C E S and PARENS-------------------------------

                'RBRACES':{
                    'i' : 'INT-i',
                    ' ' : 'q0',
                    '}' : 'RBRACES'
                },

                'LBRACES':{
                    ' ' : 'q0'
                },

                'RPAREN':{
                    ';': 'SEMICOLON',
                    ' ': 'q0',

                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                },
            #------------------F O R-------------------------------
                'FOR_F': {
                    'o' : 'FOR_O',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',
                },

                'FOR_O': {
                    'r' : 'FOR_R',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',
                },

                'FOR_R': {
                    '(' : 'FOR_LPAREN',
                    ' ' : 'FOR_*',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',

                },

                'FOR_*':{
                    '(' : 'LPAREN'
                },

                'FOR_LPAREN':{
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',
                },
            },



            #------------------S A I D A S------------------------------

              'q0',
              {
                'INT-*': "INT\n",
                'FLOAT_*': "FLOAT\n",
                'ID*'  :"ID-\n",
                'ID_COMMA': "ID\nCOMMA\n",
                'ID_RPAREN': "ID\nRPAREN\n",
                'ID_LPAREN' : "ID\nLPAREN\n",
                'ID_SEMICOLON' : "ID\nSEMICOLON\n",
                'LPAREN' : "LPAREN\n",
                'VOID_)': "VOID\nRPAREN",
                'VOID_RPAREN_LBRACES':"VOID\nRPAREN\nLBRACES\n",
                'VOID_*': "VOID\n",
                'RETURN_*' : "RETURN\n",
                'RETURN_LPAREN' : "RETURN\nLPAREN\n",
                'NUMBER_RPAREN' : "NUMBER\nRPAREN\n",
                'SEMICOLON': "SEMICOLON\n",
                'LPAREN' : "LPAREN\n",
                'PLUS' : 'PLUS\n',
                'MINUS' : 'MINUS\n',
                'TIMES' : 'TIMES\n',
                'ATTRIBUTION_*' : 'ATTRIBUTION\n',
                'RPAREN' : "RPAREN\n",
                'NUMBER_COMMA' : "NUMBER\nCOMMA\n",
                'FOR_LPAREN' : "FOR\nLPAREN\n",
                'RBRACES': "RBRACES\n",
                'LESS_*' : "LESS\n",
                'GREATER_*' : "GREATER\n",
                'EQUALS' : "EQUALS\n",
                'LESS_EQUAL' : "LESS_EQUAL\n",
                'NUMBER_SEMICOLON' : "NUMBER\nSEMICOLON\n",
                'LBRACES' : "LBRACES\n",
                'IF_*': 'IF\n',
                'ELSE_*': 'ELSE\n',
                'NUMBER_*': 'NUMBER\n',
                'ELSE_LBRACES': 'ELSE\nLBRACES\n',
                'FOR_*' : 'FOR\n',


                'q0'   : "",
                'INT-i': "",
                'INT-n': "",
                'INT-t': "",
                'ID'  : "",
                'VOID_V': "",
                'VOID_O': "",
                'VOID_I': "",
                'VOID_D': "",
                'RETURN_R':"",
                'RETURN_E':"",
                'RETURN_T':"",
                'RETURN_U':"",
                'RETURN_R2':"",
                'RETURN_N':"",
                'NUMBER':"",
                'FLOAT_F':"",
                'FLOAT_L':"",
                'FLOAT_O':"",
                'FLOAT_A':"",
                'FLOAT_T':"",
                'FOR_F':"",
                'FOR_O':"",
                'FOR_R':"",  
                'LESS':"",
                'GREATER':"", 
                'IF_I'   : "",
                'IF_F'   : "",
                'ELSE_E'   : "",
                'ELSE_L'   : "",
                'ELSE_S'   : "",
                'ELSE_E2'   : "",    
                'ATTRIBUTION' : "",       
              }
              )



args = sys.argv
file = str(args[1])
argument = FileOpen.read_file(file)

print(moore.get_output_from_string(argument))



