from automata.fa.Moore import Moore

estados = ['q0', 'INT-i', 'INT-n', 'INT-t', 'INT-*',
           'FLOAT_F', 'FLOAT_L', 'FLOAT_O', 'FLOAT_A', 'FLOAT_T', 'FLOAT_*',
            'ID', 'ID*', 'ID_LPAREN', 'LRPAREN',
            'RETURN_R','RETURN_E', 'RETURN_T', 'RETURN_U', 'RETURN_R2', 'RETURN_E', 'RETURN_N', 'RETURN_*', 'RETURN_RPAREN',
            'VOID_V', 'VOID_O', 'VOID_I', 'VOID_D', 'VOID_)', 'VOID_*', 'VOID_RPAREN_LBRACES']

lenguage = ['a','b','c','d', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0','1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '<', '>', '=']
saidas = ['INT']

moore = Moore(estados,
              lenguage,
              saidas,
              {
                #ESTADO INICIAL
                'q0':{
                    'i' : 'INT-i',          #int
                    'v' : 'VOID_V',         #VOID
                    'r' : 'RETURN_R',       #return
                    ' ' : 'q0',             #FICA EM LOOP QUANDO RE
                    '}' : 'RBRACES',        #RBRACES
                    'f' : 'FLOAT_F',        #FLOAT
                    ')' : 'LPAREN',         #LPAREN
                    '=' : 'ATTRIBUTION',    #ATTRIBUTION

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                #------------------F L O A T-------------------------
                'FLOAT_F':{
                    'l' : 'FLOAT_L',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_L':{
                    'o' : 'FLOAT_O',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_O':{
                    'a' : 'FLOAT_A',
                    
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_A':{
                    't' : 'FLOAT_T',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',   
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_T':{
                    ' ' : 'FLOAT_*',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'FLOAT_*':{
                    ' ' : 'q0',
                    
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'm' : 'ID',
                    'l' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',
                    't' : 'ID',    
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'x' : 'ID',
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                #------------------I N T-------------------------
                'INT-i':{
                    'n' : 'INT-n'
                },

                'INT-n':{
                    't' : 'INT-t'
                },

                'INT-t':{
                    ' ' : 'INT-*'
                },

                'INT-*':{
                    'a' : 'q0',
                    'b' : 'q0',
                    'c' : 'q0',
                    'd' : 'q0',
                    'e' : 'q0',
                    'f' : 'q0',
                    'g' : 'q0',
                    'h' : 'q0', 
                    'j' : 'q0', 
                    'k' : 'q0', 
                    'l' : 'q0', 
                    'm' : 'q0', 
                    'n' : 'q0',
                    'o' : 'q0', 
                    'p' : 'q0', 
                    'q' : 'q0', 
                    'r' : 'q0', 
                    's' : 'q0', 
                    't' : 'q0', 
                    'u' : 'q0', 
                    'v' : 'q0', 
                    'w' : 'q0', 
                    'y' : 'q0', 
                    'z' : 'q0', 

                },

                #------------------I D E N T I F I C A D O R-------------------------
                'ID':{
                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID',
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID', 
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 

                    ' ' : 'ID*',
                    '(' : 'ID_LPAREN',
                    ',' : 'ID_COMMA',
                    ')' : 'ID_RPAREN',
                },

                'ID_RPAREN': {
                    ' ' : 'q0',
                    ';' : 'SEMICOLON',
                },

                'ID_LPAREN':{
                    'v': 'VOID_V',
                    'i': 'INT_N',
                    ')': 'LRPAREN',
                    'f' : 'FLOAT_F',

                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                },

                'ID_COMMA':{
                    ' ': 'q0'
                },
                
                'ID*':{
                    ' ': 'q0',
                    ')': 'LPAREN',
                    '+': 'PLUS',
                    '-': 'MINUS',
                    '*': 'TIMES',
                    '=': 'ATTRIBUTION'
                },

            #---------------------S I N A I S-------------------------
            'PLUS': {
                ' ' : 'q0',
            },

            'MINUS': {
                ' ' : 'q0',
            },

            'TIMES': {
                ' ' : 'q0',
            },

            'ATTRIBUTION': {
                ' ' : 'q0',
            },

            'COMMA': {
                '0' : "NUMBER",
                '1' : "NUMBER",
                '2' : "NUMBER",
                '3' : "NUMBER",
                '4' : "NUMBER",
                '5' : "NUMBER",
                '6' : "NUMBER",
                '7' : "NUMBER",
                '8' : "NUMBER",
                '9' : "NUMBER",
            },

            #---------------------P A R E N-------------------------


                'LPAREN':{

                },

            #---------------------V O I D-------------------------

                'VOID_V':{
                    'o' : 'VOID_O',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID',
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'VOID_O':{
                    'i' : 'VOID_I',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                'VOID_I':{
                    'd' : 'VOID_D',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },

                
                'VOID_D':{
                    ' ' : 'VOID_*',
                    ')' : 'VOID_)',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID', 
                },
                
                'VOID_)':{
                    '{' : 'VOID_RPAREN_LBRACES'
                },

                'VOID_RPAREN_LBRACES':{
                    ' ' : 'q0',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },
                
                #------------------R E T U R N-------------------------

                'RETURN_R':{
                    'e' : 'RETURN_E',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'RETURN_E':{
                    't' : 'RETURN_T',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID',  
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },
                'RETURN_T':{
                    'u' : 'RETURN_U',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },
                'RETURN_U':{
                    'r' : 'RETURN_R2',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'RETURN_R2':{
                    'n' : 'RETURN_N',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',
                },

                'RETURN_N':{
                    ' ' : 'RETURN_*',
                    '(' : 'RETURN_LPAREN',

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID', 
                    'z' : 'ID',

                },

                'RETURN_LPAREN':{
                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",

                    'a' : 'ID',
                    'b' : 'ID',
                    'c' : 'ID',
                    'd' : 'ID',
                    'e' : 'ID',
                    'f' : 'ID',
                    'g' : 'ID',
                    'h' : 'ID', 
                    'i' : 'ID', 
                    'j' : 'ID', 
                    'k' : 'ID', 
                    'l' : 'ID', 
                    'm' : 'ID', 
                    'n' : 'ID',
                    'o' : 'ID',
                    'p' : 'ID', 
                    'q' : 'ID', 
                    'r' : 'ID', 
                    's' : 'ID', 
                    't' : 'ID', 
                    'u' : 'ID', 
                    'v' : 'ID', 
                    'w' : 'ID', 
                    'y' : 'ID',
                    'x' : 'ID', 
                    'z' : 'ID',

                },

            #------------------NUMBER-------------------------

                'NUMBER':{
                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                    '.' : 'NUMBER',
                    
                    ')' : "NUMBER_RPAREN",
                    ',' : "NUMBER_COMMA",
                },

                'NUMBER_COMMA':{
                    '0' : "NUMBER",
                    '1' : "NUMBER",
                    '2' : "NUMBER",
                    '3' : "NUMBER",
                    '4' : "NUMBER",
                    '5' : "NUMBER",
                    '6' : "NUMBER",
                    '7' : "NUMBER",
                    '8' : "NUMBER",
                    '9' : "NUMBER",
                },

                'NUMBER_RPAREN':{
                    ';' : "SEMICOLON",
                },

            #------------------S E M I C O L O N-------------------------

                'SEMICOLON':{
                    ' ' : "q0",
                    '}' : 'RBRACES'
                },

            #------------------B R A C E S and PARENS-------------------------------

                'RBRACES':{
                    'i' : 'INT-i'
                },

                'RPAREN':{

                },


              },



            #------------------S A I D A S------------------------------

              'q0',
              {
                'INT-*': "INT\n",
                'FLOAT_*': "FLOAT\n",
                'ID*'  :"ID-\n",
                'ID_COMMA': "ID\nCOMMA\n",
                'ID_RPAREN': "ID\nRPAREN\n",
                'ID_LPAREN' : "ID\nLPAREN\n",
                'LRPAREN' : "ID\nLPAREN\nRPAREN\n",
                'VOID_)': "VOID\nRPAREN",
                'VOID_RPAREN_LBRACES':"VOID\nRPAREN\nLBRACES\n",
                'VOID_*': "VOID\n",
                'RETURN_*' : "RETURN\n",
                'RETURN_LPAREN' : "RETURN\nLPAREN\n",
                'NUMBER_RPAREN' : "NUMBER\nRPAREN\n",
                'SEMICOLON': "SEMICOLON\n",
                'LPAREN' : "LPAREN\n",
                'PLUS' : 'PLUS\n',
                'MINUS' : 'MINUS\n',
                'TIMES' : 'TIMES\n',
                'ATTRIBUTION' : 'ATTRIBUTION\n',
                'RPAREN' : "RPAREN\n",
                'NUMBER_COMMA' : "NUMBER\nCOMMA\n",
                'RBRACES': "RBRACES\n",


                'q0'   : "",
                'INT-i': "",
                'INT-n': "",
                'INT-t': "",
                'ID'  : "",
                'VOID_V': "",
                'VOID_O': "",
                'VOID_I': "",
                'VOID_D': "",
                'RETURN_R':"",
                'RETURN_E':"",
                'RETURN_T':"",
                'RETURN_U':"",
                'RETURN_R2':"",
                'RETURN_N':"",
                'NUMBER':"",
                'FLOAT_F':"",
                'FLOAT_L':"",
                'FLOAT_O':"",
                'FLOAT_A':"",
                'FLOAT_T':"",
              }
              )



print(moore.get_output_from_string('float soma(float x, float x)  return(x + y);}int main(void){  float res = soma(5.0,9.5);}'))

